const GET_CATEGORIES = "@authType/GET_CATEGORIES"
const SET_CATEGORIES = "@authType/SET_CATEGORIES"
const DELETE_CATEGORI = "@authType/DELETE_CATEGORI"

export {GET_CATEGORIES,SET_CATEGORIES,DELETE_CATEGORI}