 const GET_DOCTORS = '@doctorTypes/GET_DOCTORS'
 const SET_DOCTORS = '@doctorTypes/SET_DOCTORS'
 const GET_SELECTED_DOCTOR = '@doctorTypes/GET_SELECTED_DOCTOR'
 const SET_SELECTED_DOCTOR = '@doctorTypes/SET_SELECTED_DOCTOR'
 const CHANGE_DOCTOR = '@doctorTypes/CHANGE_DOCTOR'
 const UPDATE_DOCTOR_INFO = '@doctorTypes/UPDATE_DOCTOR_INFO'

 export {
    GET_DOCTORS,
    SET_DOCTORS,
    GET_SELECTED_DOCTOR,
    SET_SELECTED_DOCTOR,
    CHANGE_DOCTOR,
    UPDATE_DOCTOR_INFO
}